model:
  model_id: video_dito
  sample_size: [160,320]
  channels: 3
  latent_size: 16
  latent_channels: 32

  ch_0: 96
  ch_max: 384

  encoder_blocks_per_stage: [2, 2]
  decoder_blocks_per_stage: [2, 2]

  n_layers: 24
  n_heads: 16
  d_model: 1024

  patch_size: [5, 10]
  x0_mode: true
  temporal_factor: 4
  n_frames: 8
  decoder_kernel: [4, 4]


train:
  trainer_id: video_dito
  data_id: video_dir_loader
  data_kwargs:
    source:
     - /mnt/data/waypoint_1/data/MKIF/*/*.mp4 
     - /mnt/data/datasets/extracted_tars/kbm/fps/*/*.mp4
     - /mnt/data/datasets/extracted_tars/kbm/3ps/*/*.mp4
     - /mnt/data/datasets/extracted_tars/kbm/other/*/*.mp4
    target_size: [160, 320]
    window_length: 16

  target_batch_size: 64
  batch_size: 8

  epochs: 200

#  opt: AdamW
#  opt_kwargs:
#    lr: 3.0e-5
#    betas: [0.9, 0.99]
#    eps: 1.0e-6

  opt: Muon
  opt_kwargs:
    lr: 2.5e-4
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-2
    adamw_eps: 1.0e-6
    adamw_betas: [0.9, 0.999]
    adamw_keys:
      - encoder.conv_in
      - encoder.conv_out
      - .residuals.
      - .temp_downs.
      - .decoder.proj_in
      - .decoder.proj_out
      - .decoder.ts_embed
      - .decoder.final
      - .adaln1
      - .adaln2
      - .gate1
      - .gate2
  
  loss_weights:
    opl: 0.0

#  lpips_type: convnext
#  loss_weights:
#    lpips: 12.0
#    l2: 1.0
#    dwt: 0.25
#    opl: 0.0 #1.0e+4

  scheduler: LinearWarmupWithCosineDecay
  scheduler_kwargs:
    warmup_steps: 3000
    decay_after: 120000
    decay_steps: 220000
    start_mult: 0.1
    decay_to_mult: 0.1

  checkpoint_dir: checkpoints/waypoint_1_vae_owlc_f16_c16_video_dito_huge
  resume_ckpt: null #checkpoints/waypoint_1_vae_owlc_f16_c16_video_dito/step_5000.pt

  sample_interval: 500
  save_interval: 5000
  sampling_steps: 30
  use_proxy: false

  n_samples: 8
  sample_fps: 30
  sample_window_length: 60


wandb:
  name: shahbuland
  project: video_vaes
  run_name: waypoint_1_vae_owlc_f16_c16_video_dito