model:
  model_id: dcae
  sample_size: [360, 640]
  channels: 3
  latent_size: 32
  latent_channels: 16

  ch_0: 256
  ch_max: 2048

  encoder_blocks_per_stage: [4, 4, 4, 8]
  decoder_blocks_per_stage: [4, 4, 4, 8]

  use_middle_block: false
  do_channel_mask: false

train:
  trainer_id: rec
  data_id: video_dir_loader
  data_kwargs:
    source:
     - /mnt/data/laplace/datasets/t3_dataset_main_mp4
    # - /mnt/data/datasets/extracted_tars/kbm/3ps/*/*.mp4
    #- /mnt/data/datasets/extracted_tars/kbm/other/*/*.mp4
    target_size: [360, 640]

  target_batch_size: 32
  batch_size: 4

  epochs: 200

  #opt: AdamW
  #opt_kwargs:
  #  lr: 3.0e-5
  #  weight_decay: 1.0e-4
 #   betas: [0.9, 0.95]
 #   eps: 1.0e-15

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-5
    adamw_wd: 1.0e-2
    adamw_eps: 1.0e-6
    adamw_betas: [0.9, 0.95]
    adamw_keys:
      - encoder.conv_in
      - encoder.conv_out
      - encoder.conv_out_logvar
      - decoder.conv_in
      - decoder.conv_out
      - .up.
      - .down.
      - .residuals.

  lpips_type: convnext
  loss_weights:
    kl: 3.0e-7
    lpips: 12.0
    l2: 1.0
    dwt: 0.25


  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 3000
    min_lr: 1.0e-5

  checkpoint_dir: /mnt/data/shahbuland/owl-vaes/checkpoints/waypoint_1_vae_owlc_f16_c16
  resume_ckpt: /mnt/data/shahbuland/owl-vaes/checkpoints/waypoint_1_vae_owlc_f16_c16/step_300000.pt

  sample_interval: 1000
  save_interval: 5000

wandb:
  name: d-fusion
  project: tekken_vae_finetuning_v1
  run_name:  vae_finetuning